### ISSUE TITLE
Errors: when running `yarn serve` command

### ISSUE THREAD

**Issue by theseusyang1** [emqx/neuron-dashboard#266]
INFO  Starting development server...
10% building 2/2 modules 0 active ERROR  TypeError: Cannot read properties of undefined (reading 'upgrade')
TypeError: Cannot read properties of undefined (reading 'upgrade')
    at Server.<anonymous> (/Users/theseusyang/代码/neuron-dashboard/node_modules/webpack-dev-server/lib/Server.js:135:47)
    at Array.forEach (<anonymous>)
    at new Server (/Users/theseusyang/代码/neuron-dashboard/node_modules/webpack-dev-server/lib/Server.js:134:27)
    at serve (/Users/theseusyang/代码/neuron-dashboard/node_modules/@vue/cli-service/lib/commands/serve.js:172:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by orangegzx** [comment]
> INFO Starting development server... 10% building 2/2 modules 0 active ERROR TypeError: Cannot read properties of undefined (reading 'upgrade') TypeError: Cannot read properties of undefined (reading 'upgrade') at Server. (/Users/theseusyang/代码/neuron-dashboard/node_modules/webpack-dev-server/lib/Server.js:135:47) at Array.forEach () at new Server (/Users/theseusyang/代码/neuron-dashboard/node_modules/webpack-dev-server/lib/Server.js:134:27) at serve (/Users/theseusyang/代码/neuron-dashboard/node_modules/@vue/cli-service/lib/commands/serve.js:172:20) at processTicksAndRejections (node:internal/process/task_queues:96:5) error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

This is because the `devServer` in vue.config.js has set the proxy,  but the `target` is empty.  you can set a address to solve.

**Comment by orangegzx** [comment]
please check if you have set the `VUE_APP_HOST`.
