### ISSUE TITLE
Neuron Dashboard 2.3.3 Released:  can not create 南向设备和北向设备

### ISSUE THREAD

**Issue by xufei2222** [emqx/neuron-dashboard#324]
点击创建的南向设备或者北向设备，均会出现错误码1002：请求body无效。neuron用的是最新提交代码

**Comment by orangegzx** [comment]
> 点击创建的南向设备或者北向设备，均会出现错误码1002：请求body无效。neuron用的是最新提交代码

前端最新版本包括了2.4.0的功能，后端也需要使用对应版本，不然可能会出现一些问题。

**Comment by xufei2222** [comment]
谢谢。前端源码编译能否提供文档，我按照readme里编译没通过。发自我的荣耀手机-------- 原始邮件 --------发件人： orangegzx ***@***.***>日期： 2023年2月7日周二 19:01收件人： emqx/neuron-dashboard ***@***.***>抄送： xufei2222 ***@***.***>, Author ***@***.***>主    题： Re: [emqx/neuron-dashboard] Neuron Dashboard 2.3.3 Released:  can not create 南向设备和北向设备 (Issue #324)



点击创建的南向设备或者北向设备，均会出现错误码1002：请求body无效。neuron用的是最新提交代码



前端最新版本包括了2.4.0的功能，后端也需要使用对应版本，不然可能会出现一些问题。
